"""first migration

Revision ID: cf6229c2c600
Revises: 
Create Date: 2017-12-27 21:51:45.720046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6229c2c600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drafts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('player_pk', sa.Integer(), nullable=True),
    sa.Column('team_pk', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('pick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_pk'], ['players.pk'], ),
    sa.ForeignKeyConstraint(['team_pk'], ['teams.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('games',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_pk', sa.Integer(), nullable=False),
    sa.Column('away_team_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_pk'], ['teams.pk'], ),
    sa.ForeignKeyConstraint(['home_team_pk'], ['teams.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('player_performances',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('yards', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('touchdowns', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.pk'], ),
    sa.ForeignKeyConstraint(['player_pk'], ['players.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_performances')
    op.drop_table('games')
    op.drop_table('drafts')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
